set-option -sa terminal-overrides ",xterm*:Tc"
unbind C-b
set -g prefix M-x
bind M-x send-prefix
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

set -g @plugin 'tmux-plugin/tpm'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugin/tmux-resurrect'

set -g @catppuccin_flavour 'mocha'
set -g @catppuccin_window_status_icon_enable "yes"

run '~/.tmux/plugins/tpm/tpm'
